# Generated by Django 4.1 on 2022-09-14 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_incidents_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidents',
            name='query_type',
            field=models.CharField(choices=[('MC', 'Medical Certificate'), ('CG', 'Compassionate Grounds'), ('W', 'Waive')], default='MC', max_length=2),
            preserve_default=False,
        ),
    ]
