# Generated by Django 4.1 on 2022-09-28 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0004_alter_incidents_query_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidents',
            name='query_type',
            field=models.CharField(choices=[('Medical Certificate', 'Medical Certificate'), ('Compassionate Grounds', 'Compassionate Grounds'), ('Waive', 'Waive')], default='MC', max_length=30),
        ),
    ]
