# Generated by Django 4.1 on 2022-09-06 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.CharField(max_length=9)),
                ('assignmentOne', models.CharField(max_length=3)),
                ('assignmentTwo', models.CharField(max_length=3)),
                ('assignmentThree', models.CharField(max_length=3)),
                ('assignmentFour', models.CharField(max_length=3)),
                ('assignmentFive', models.CharField(max_length=3)),
                ('assignmentSix', models.CharField(max_length=3)),
                ('testOne', models.CharField(max_length=3)),
                ('testTwo', models.CharField(max_length=3)),
                ('assignmentAverage', models.CharField(max_length=3)),
                ('testAverage', models.CharField(max_length=3)),
                ('finalMark', models.CharField(max_length=3)),
            ],
        ),
    ]
