# Generated by Django 4.1 on 2022-09-06 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentResults', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='assignmentAverage',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='assignmentFive',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='assignmentFour',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='assignmentOne',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='assignmentSix',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='assignmentThree',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='assignmentTwo',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='finalMark',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='testAverage',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='testOne',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='testTwo',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
