# Generated by Django 4.1 on 2022-09-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentResults', '0003_alter_student_assignmentaverage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_number',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
