# Generated by Django 4.1 on 2022-09-06 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentResults', '0004_alter_student_student_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_number',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
