# Generated by Django 4.1 on 2022-09-06 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentResults', '0005_alter_student_student_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_number',
            new_name='studentNumber',
        ),
    ]
