# Generated by Django 4.1 on 2022-09-14 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentResults', '0006_rename_student_number_student_studentnumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='assignmentFive',
            new_name='assignment1',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='assignmentFour',
            new_name='assignment2',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='assignmentOne',
            new_name='assignment3',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='assignmentSix',
            new_name='assignment4',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='assignmentThree',
            new_name='assignment5',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='assignmentTwo',
            new_name='assignment6',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='testOne',
            new_name='test1',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='testTwo',
            new_name='test2',
        ),
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='studentNumber',
            field=models.CharField(default=0, max_length=3, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='testAverage',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
