# Generated by Django 4.1 on 2022-09-14 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentResults', '0008_alter_student_studentnumber_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='assignment1',
            new_name='assignmentFive',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='assignment2',
            new_name='assignmentFour',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='assignment3',
            new_name='assignmentOne',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='assignment4',
            new_name='assignmentSix',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='assignment5',
            new_name='assignmentThree',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='assignment6',
            new_name='assignmentTwo',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='test1',
            new_name='testOne',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='test2',
            new_name='testTwo',
        ),
        migrations.AlterField(
            model_name='student',
            name='studentNumber',
            field=models.CharField(default='no value', max_length=3, primary_key=True, serialize=False),
        ),
    ]
