# Generated by Django 4.1 on 2022-09-28 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentResults', '0009_rename_assignment1_student_assignmentfive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='testAverage',
            field=models.IntegerField(blank=True, max_length=3, null=True),
        ),
    ]
