# Generated by Django 4.1 on 2022-09-28 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentResults', '0010_alter_student_testaverage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='assignmentAverage',
            field=models.IntegerField(blank=True, max_length=3, null=True),
        ),
    ]
