# Generated by Django 4.1 on 2022-09-08 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutor_Marking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor_marking',
            name='A1_Marker',
            field=models.CharField(choices=[('default tutor', 'Select a Tutor'), ('BNDJAM007', 'Tutor is default'), ('TRMDON002', 'Tutor is default'), ('JHNBOR002', 'Tutor is default'), ('MNDNEL001', 'Tutor is default'), ('ZMXJAC003', 'Tutor is default'), ('RMPCYR004', 'Tutor is default'), ('NHXTRE001', 'Tutor is default'), ('RBNNIC005', 'Tutor is default'), ('LTTMAR002', 'Tutor is default'), ('PWRAUS003', 'Tutor is default'), ('MBKTHA002', 'Tutor is default'), ('CRRJIM004', 'Tutor is default'), ('JHNBOR002', 'Tutor is default')], default='default tutor', max_length=15),
        ),
        migrations.AlterField(
            model_name='tutor_marking',
            name='A2_Marker',
            field=models.CharField(choices=[('default tutor', 'Select a Tutor'), ('BNDJAM007', 'Tutor is default'), ('TRMDON002', 'Tutor is default'), ('JHNBOR002', 'Tutor is default'), ('MNDNEL001', 'Tutor is default'), ('ZMXJAC003', 'Tutor is default'), ('RMPCYR004', 'Tutor is default'), ('NHXTRE001', 'Tutor is default'), ('RBNNIC005', 'Tutor is default'), ('LTTMAR002', 'Tutor is default'), ('PWRAUS003', 'Tutor is default'), ('MBKTHA002', 'Tutor is default'), ('CRRJIM004', 'Tutor is default'), ('JHNBOR002', 'Tutor is default')], default='default tutor', max_length=15),
        ),
        migrations.AlterField(
            model_name='tutor_marking',
            name='A3_Marker',
            field=models.CharField(choices=[('default tutor', 'Select a Tutor'), ('BNDJAM007', 'Tutor is default'), ('TRMDON002', 'Tutor is default'), ('JHNBOR002', 'Tutor is default'), ('MNDNEL001', 'Tutor is default'), ('ZMXJAC003', 'Tutor is default'), ('RMPCYR004', 'Tutor is default'), ('NHXTRE001', 'Tutor is default'), ('RBNNIC005', 'Tutor is default'), ('LTTMAR002', 'Tutor is default'), ('PWRAUS003', 'Tutor is default'), ('MBKTHA002', 'Tutor is default'), ('CRRJIM004', 'Tutor is default'), ('JHNBOR002', 'Tutor is default')], default='default tutor', max_length=15),
        ),
        migrations.AlterField(
            model_name='tutor_marking',
            name='A4_Marker',
            field=models.CharField(choices=[('default tutor', 'Select a Tutor'), ('BNDJAM007', 'Tutor is default'), ('TRMDON002', 'Tutor is default'), ('JHNBOR002', 'Tutor is default'), ('MNDNEL001', 'Tutor is default'), ('ZMXJAC003', 'Tutor is default'), ('RMPCYR004', 'Tutor is default'), ('NHXTRE001', 'Tutor is default'), ('RBNNIC005', 'Tutor is default'), ('LTTMAR002', 'Tutor is default'), ('PWRAUS003', 'Tutor is default'), ('MBKTHA002', 'Tutor is default'), ('CRRJIM004', 'Tutor is default'), ('JHNBOR002', 'Tutor is default')], default='default tutor', max_length=15),
        ),
        migrations.AlterField(
            model_name='tutor_marking',
            name='A5_Marker',
            field=models.CharField(choices=[('default tutor', 'Select a Tutor'), ('BNDJAM007', 'Tutor is default'), ('TRMDON002', 'Tutor is default'), ('JHNBOR002', 'Tutor is default'), ('MNDNEL001', 'Tutor is default'), ('ZMXJAC003', 'Tutor is default'), ('RMPCYR004', 'Tutor is default'), ('NHXTRE001', 'Tutor is default'), ('RBNNIC005', 'Tutor is default'), ('LTTMAR002', 'Tutor is default'), ('PWRAUS003', 'Tutor is default'), ('MBKTHA002', 'Tutor is default'), ('CRRJIM004', 'Tutor is default'), ('JHNBOR002', 'Tutor is default')], default='default tutor', max_length=15),
        ),
        migrations.AlterField(
            model_name='tutor_marking',
            name='A6_Marker',
            field=models.CharField(choices=[('default tutor', 'Select a Tutor'), ('BNDJAM007', 'Tutor is default'), ('TRMDON002', 'Tutor is default'), ('JHNBOR002', 'Tutor is default'), ('MNDNEL001', 'Tutor is default'), ('ZMXJAC003', 'Tutor is default'), ('RMPCYR004', 'Tutor is default'), ('NHXTRE001', 'Tutor is default'), ('RBNNIC005', 'Tutor is default'), ('LTTMAR002', 'Tutor is default'), ('PWRAUS003', 'Tutor is default'), ('MBKTHA002', 'Tutor is default'), ('CRRJIM004', 'Tutor is default'), ('JHNBOR002', 'Tutor is default')], default='default tutor', max_length=15),
        ),
    ]
