# Generated by Django 4.1 on 2022-09-11 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutor_Marking', '0005_alter_tutor_marking_a1_marker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor_marking',
            name='A1_Marker',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='tutor_marking',
            name='A2_Marker',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='tutor_marking',
            name='A3_Marker',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='tutor_marking',
            name='A4_Marker',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='tutor_marking',
            name='A5_Marker',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='tutor_marking',
            name='A6_Marker',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='tutor_marking',
            name='Student',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
