# Generated by Django 4.1 on 2022-09-15 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutor_Marking', '0006_alter_tutor_marking_a1_marker_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor_marking',
            name='id',
        ),
        migrations.AlterField(
            model_name='tutor_marking',
            name='Student',
            field=models.CharField(default='no value', max_length=5, primary_key=True, serialize=False),
        ),
    ]
