# Generated by Django 4.1 on 2022-09-15 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tutor_Marking', '0007_remove_tutor_marking_id_alter_tutor_marking_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutor_marking',
            old_name='Student',
            new_name='student',
        ),
    ]
