# Generated by Django 4.1 on 2022-09-28 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutor_Marking', '0008_rename_student_tutor_marking_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor_marking',
            name='student',
            field=models.CharField(default='no value', max_length=3, primary_key=True, serialize=False),
        ),
    ]
